services:
  db:
    image: postgres:17
    env_file: .env
    volumes:
      - postgres_data:/var/lib/postgresql/data

  web:
    image: guild-wars-catalog:latest
    build: .
    env_file: .env
    ports:
      - '8000:8000'
    volumes:
      - '.:/app'

volumes:
  postgres_data:
