name: gwc-backend

services:
  db:
    image: postgres:17
    container_name: gwc-backend-db
    env_file: .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 5s
      timeout: 5s
    networks:
      - gwc-network

  web:
    image: gwc-backend:dev
    container_name: gwc-backend-web
    build:
      context: .
      dockerfile: Dockerfile.dev
    env_file: .env
    depends_on:
      db:
        condition: service_healthy
    ports:
      - '8000:8000'
    volumes:
      - '.:/app'
    networks:
      - gwc-network

volumes:
  postgres_data:

networks:
  gwc-network:
    external: true
