# Generated by Django 5.2.4 on 2025-09-04 10:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Release',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, unique=True)),
                ('slug', models.SlugField(max_length=40, unique=True)),
                ('order', models.PositiveSmallIntegerField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=20)),
                ('note', models.CharField(max_length=255)),
                ('release', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='collections', to='catalog.release')),
            ],
        ),
        migrations.CreateModel(
            name='Skin',
            fields=[
                ('api_id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=20)),
                ('details', models.JSONField(default=dict)),
                ('is_unlocked', models.BooleanField(default=False)),
                ('collection', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='skins', to='catalog.collection')),
            ],
        ),
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, unique=True)),
                ('slug', models.SlugField(max_length=40, unique=True)),
                ('order', models.PositiveSmallIntegerField()),
                ('release', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='zones', to='catalog.release')),
            ],
        ),
        migrations.AddField(
            model_name='collection',
            name='zone',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='collections', to='catalog.zone'),
        ),
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('api_id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('requirement', models.TextField()),
                ('is_unlocked', models.BooleanField(default=False)),
                ('release', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='achievements', to='catalog.release')),
                ('zone', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='achievements', to='catalog.zone')),
            ],
        ),
    ]
